#!/usr/bin/env python3                                                    
# -*- coding: latin-1 -*-                                                 

try:
    import sys
except:
    print ("Error: Cannot load lib 'sys'", file=sys.stderr)
    sys.exit(84)

def usage():
    print ("USAGE")
    print("\t./205IQ u 6 [IQ1][IQ2]")
    print("")
    print("DESCRIPTION")
    print("\tu\tpredetermined mean")
    print("\t6\tpredetermined standart deviation")
    print("\tIQ1\tminimum IQ")
    print("\tIQ2\tmaximum IQ")    
    sys.exit(84)


if __name__ == '__main__':
    if (len(sys.argv) != 2):
        usage()
